name: Integration Tests

on:
  pull_request: # Run on all pull requests
  push:
    branches:   # Run on any push to master and development
      - master
      - development
  schedule:     # Run weekly on master and development
    - cron: 0 2 * * 0
      branches: master
    - cron: 0 2 * * 0
      branches: development


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_COMMITS: '--resfinder-commit 149209df6444c539512111335e575baa1ff1ed24 --pointfinder-commit 4baff38db48f4994ba833345f699c0e7781e6c42 --plasmidfinder-commit 81919954cbedaff39056610ab584ab4c06011ed8'
    
    strategy:
      fail-fast: False
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda with Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: foo
          python-version: ${{ matrix.python-version }}

      - name: Install conda packages
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --add channels defaults
          conda config --add channels conda-forge
          conda config --add channels bioconda
          conda install blast=2.7.1 git mlst -y

      - name: Setup python packages
        shell: bash -l {0}
        run: |
          python --version
          python setup.py -q install
          pip install pandas==0.25.3 mypy==0.600

      - name: Build database
        shell: bash -l {0}
        run: staramr db build --dir staramr/databases/data ${{ env.DATABASE_COMMITS }}

      - name: Run Tests
        shell: bash -l {0}
        run: ./scripts/mypy && python setup.py test
